package com.uranus.platform.business.ws.login;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "InfWsLogin", targetNamespace = "http://ws.inf.creditapp.app/")
public interface InfWsLogin {

	/**
	 * 
	 * @param request
	 * @return returns app.creditapp.inf.ws.Response
	 */
	@WebMethod
	@WebResult(name = "response", targetNamespace = "")
	@RequestWrapper(localName = "login", targetNamespace = "http://ws.inf.creditapp.app/", className = "com.uranus.platform.business.ws.login.Login")
	@ResponseWrapper(localName = "loginResponse", targetNamespace = "http://ws.inf.creditapp.app/", className = "com.uranus.platform.business.ws.login.LoginResponse")
	public Response login(
			@WebParam(name = "request", targetNamespace = "") LoginRequest request);

}
