package com.uranus.platform.business.ws.process;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "InfWsProcess", targetNamespace = "http://ws.inf.creditapp.app/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface InfWsProcess {


    /**
     * 
     * @param request
     * @return
     *     returns com.dhcc.ws.process.Response
     */
    @WebMethod
    @WebResult(name = "response", targetNamespace = "")
    @RequestWrapper(localName = "process", targetNamespace = "http://ws.inf.creditapp.app/", className = "com.uranus.platform.business.ws.process.Process")
    @ResponseWrapper(localName = "processResponse", targetNamespace = "http://ws.inf.creditapp.app/", className = "com.uranus.platform.business.ws.process.ProcessResponse")
    public Response process(
        @WebParam(name = "request", targetNamespace = "")
        Request request);

}
